/**
 * generated by Xtext
 */
package org.xtext.java.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
public class JavaDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
