/*
 * generated by Xtext
 */
package org.xtext.java.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JavaUiModule extends org.xtext.java.ui.AbstractJavaUiModule {
	public JavaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
