/**
 * generated by Xtext
 */
package org.xtext.java.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
public class JavaQuickfixProvider extends DefaultQuickfixProvider {
}
