/*
 * generated by Xtext
 */
package org.xtext.java.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.java.ui.internal.JavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JavaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JavaActivator.getInstance().getInjector(JavaActivator.ORG_XTEXT_JAVA_JAVA);
	}
	
}
