/**
 * generated by Xtext
 */
package org.xtext.java.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class JavaScopeProvider /* implements org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider  */{
}
