/*
 * generated by Xtext
 */
package org.xtext.java;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JavaRuntimeModule extends org.xtext.java.AbstractJavaRuntimeModule {

}
